### ISSUE TITLE
The content of main overlapping with footer 

### ISSUE THREAD

**Issue by sergiucoman** [hlxsites/troweprice-rf#26]
The main content is overlapping with footer. This is due to the following line of code: 

https://github.com/hlxsites/troweprice-rf/blob/b63eacf729f314393bfaacf51a78a6b84b3ae6e6/styles/styles.css#L78

**Comment by dnbute** [comment]
This was solved in this PR https://github.com/hlxsites/troweprice-rf/pull/23
